# Generated by Django 2.0.7 on 2018-07-21 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zinnia', '0004_on_delete_arg'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('visible', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, help_text='Used for illustration.', upload_to='uploads/zinnia', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='ForumThreadForEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.IntegerField()),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum_thread', to='zinnia.Entry')),
            ],
        ),
    ]
