# Generated by Django 2.0.7 on 2018-07-21 12:44

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='screenshots')),
                ('displayed', models.BooleanField(default=True)),
                ('promoted', models.BooleanField(default=False)),
            ],
        ),
    ]
