# Generated by Django 2.0.7 on 2018-07-21 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_system', models.CharField(db_index=True, max_length=64)),
                ('url', models.URLField(null=True)),
                ('user_os_matcher', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='BranchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadableVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevVersion',
            fields=[
                ('downloadableversion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='downloads.DownloadableVersion')),
                ('branch', models.CharField(db_index=True, max_length=64)),
                ('shortrev', models.CharField(max_length=64)),
                ('hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('author', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
            bases=('downloads.downloadableversion',),
        ),
        migrations.CreateModel(
            name='ReleaseVersion',
            fields=[
                ('downloadableversion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='downloads.DownloadableVersion')),
                ('version', models.CharField(max_length=64)),
            ],
            bases=('downloads.downloadableversion',),
        ),
        migrations.AddField(
            model_name='artifact',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='downloads.DownloadableVersion'),
        ),
        migrations.AlterUniqueTogether(
            name='artifact',
            unique_together={('version', 'target_system')},
        ),
        migrations.AlterIndexTogether(
            name='artifact',
            index_together={('version', 'target_system')},
        ),
    ]
